version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: hazem
      POSTGRES_PASSWORD: hazem
      POSTGRES_DB: reservation_system
    ports:
      - 5444:5432
    restart: always

