spring:
  application:
    name: BuggyApp
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: hazem
    password: hazem
    url: jdbc:postgresql://localhost:5444/reservation_system
    driver-class-name: org.postgresql.Driver
server:
  port: 8083